### ISSUE TITLE
Create a story board for the architecture

### ISSUE THREAD

**Issue by gaaliciA1990** [DerpCompany/Derp_Site#12]
Requirements
- [x] Create a wiki page with the design
- [x] PlantUML diagram (modifiable)

Details
High level architectural design and state machine for the website

**Comment by CRamsan** [comment]
Workflow: https://github.com/DerpCompany/Derp_Site/wiki/Site-Workflow

Server Architecture: https://github.com/DerpCompany/Derp_Site/wiki/Architecture
